version: '3.8'

services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: ./.docker/db/Dockerfile
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./.cartesi/data:/var/lib/postgresql/data
    networks:
      cartesi-net:
        aliases:
          - cartesi-db
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"

networks:
  cartesi-net:
    name: cartesi-net
