[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
optimize = true
optimizer_runs = 200
solc = "0.8.21"

ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

[profile.dependencies]
"@openzepplin-contracts" = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts.git", tag = "v5.0.1" }
"@openzepplin-contracts-upgradeable" = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable.git", tag = "v5.0.1" }